 hpc<-read.table("household_power_consumption.txt",header = TRUE, sep=";",colClasses=c("Global_reactive_power"="numeric","Sub_metering_1"="numeric","Sub_metering_2"="numeric","Sub_metering_3"="numeric"),na.strings="?")
 hpcsubset<-subset(hpc,Date %in% c("1/2/2007","2/2/2007"))
 hpcdt_tmp<-paste(hpcsubset$Date,hpcsubset$Time)
 hpcdym_tmp<-strptime(hpcdt_tmp,format="%d/%m/%Y %H:%M:%S")
 png(file="Plot3.png",height=480,width=480)
 plot( hpcdym_tmp,hpcsubset$Sub_metering_1,ylab="Energy sub metering",xlab="",type="l")
 points( hpcdym_tmp,hpcsubset$Sub_metering_2,type="l",col="red")
 points( hpcdym_tmp,hpcsubset$Sub_metering_3,type="l",col="blue")
 legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=c(1,1,1))
 dev.off()
